name: Build Windows Executable

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        # Cache parameter removed to avoid requirements.txt issue

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy pandas matplotlib scipy tqdm pyinstaller

    - name: Create resource_path.py helper file
      shell: cmd
      run: |
        echo import os > resource_path.py
        echo import sys >> resource_path.py
        echo. >> resource_path.py
        echo def resource_path(relative_path): >> resource_path.py
        echo     """Get absolute path to resource, works for dev and for PyInstaller""" >> resource_path.py
        echo     try: >> resource_path.py
        echo         # PyInstaller creates a temp folder and stores path in _MEIPASS >> resource_path.py
        echo         base_path = sys._MEIPASS >> resource_path.py
        echo     except Exception: >> resource_path.py
        echo         base_path = os.path.abspath(".") >> resource_path.py
        echo. >> resource_path.py
        echo     return os.path.join(base_path, relative_path) >> resource_path.py

    - name: Create modified app.py
      shell: cmd
      working-directory: current_app
      run: |
        copy ..\resource_path.py + app.py app_temp.py
        move /y app_temp.py app.py
        type app.py

    - name: Modify CSV loading in app.py
      shell: powershell
      working-directory: current_app
      run: |
        (Get-Content app.py) -replace "df = pd\.read_csv\('combined\.csv'\)", "df = pd.read_csv(resource_path('combined.csv'))" | Set-Content app.py

    - name: Build with PyInstaller
      working-directory: current_app
      run: |
        pyinstaller --onefile --add-data "combined.csv;." app.py --name "TennisPointByPoint"

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: TennisPointByPoint
        path: current_app/dist/TennisPointByPoint.exe
        retention-days: 30
