name: Build Windows Executable

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy pandas matplotlib scipy tqdm pyinstaller

    - name: Prepare app.py
      shell: powershell
      working-directory: current_app
      run: |
        # Create temporary file with resource_path function
        $resourcePath = @"
import os
import sys

def resource_path(relative_path):
    """Get absolute path to resource, works for dev and for PyInstaller"""
    try:
        # PyInstaller creates a temp folder and stores path in _MEIPASS
        base_path = sys._MEIPASS
    except Exception:
        base_path = os.path.abspath(".")

    return os.path.join(base_path, relative_path)

"@

        # Read the current app.py content
        $appContent = Get-Content -Raw app.py
        
        # Create a new file with resource_path function followed by original content
        Set-Content -Path app_modified.py -Value "$resourcePath`n$appContent"
        
        # Replace CSV loading line
        (Get-Content app_modified.py) -replace "df = pd\.read_csv\('combined\.csv'\)", "df = pd.read_csv(resource_path('combined.csv'))" | Set-Content app_modified.py
        
        # Display first 50 lines for debugging
        Get-Content app_modified.py -TotalCount 50
        
        # Rename to app.py
        Move-Item -Force app_modified.py app.py

    - name: Build with PyInstaller
      working-directory: current_app
      run: |
        pyinstaller --onefile --add-data "combined.csv;." app.py --name "TennisPointByPoint"

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: TennisPointByPoint
        path: current_app/dist/TennisPointByPoint.exe
        retention-days: 30
