name: Build Windows Executable

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy pandas matplotlib scipy tqdm pyinstaller

    - name: Create patch script
      run: |
        echo import os, sys, re > patch_app.py
        echo def add_resource_path(app_path): >> patch_app.py
        echo     with open(app_path, 'r') as f: >> patch_app.py
        echo         content = f.read() >> patch_app.py
        echo     resource_func = '''import os\nimport sys\n\ndef resource_path(relative_path):\n    """Get absolute path to resource, works for dev and for PyInstaller"""\n    try:\n        # PyInstaller creates a temp folder and stores path in _MEIPASS\n        base_path = sys._MEIPASS\n    except Exception:\n        base_path = os.path.abspath(".")\n\n    return os.path.join(base_path, relative_path)\n''' >> patch_app.py
        echo     patched_content = resource_func + "\n\n" + content >> patch_app.py
        echo     patched_content = re.sub(r"df = pd\.read_csv\('combined\.csv'\)", "df = pd.read_csv(resource_path('combined.csv'))", patched_content) >> patch_app.py
        echo     with open(app_path, 'w') as f: >> patch_app.py
        echo         f.write(patched_content) >> patch_app.py
        echo if __name__ == '__main__': >> patch_app.py
        echo     add_resource_path('current_app/app.py') >> patch_app.py

    - name: Patch app.py
      run: python patch_app.py

    - name: Build with PyInstaller
      working-directory: current_app
      run: |
        pyinstaller --onefile --add-data "combined.csv;." app.py --name "TennisPointByPoint"

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: TennisPointByPoint
        path: current_app/dist/TennisPointByPoint.exe
        retention-days: 30
